// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrQcFYNiIBD8JPJP6m_XHiVtmlJRpuf3E',
    appId: '1:275997925238:web:aa8965e2be77d7158aa457',
    messagingSenderId: '275997925238',
    projectId: 'edumate-4a475',
    authDomain: 'edumate-4a475.firebaseapp.com',
    databaseURL: 'https://edumate-4a475-default-rtdb.firebaseio.com',
    storageBucket: 'edumate-4a475.appspot.com',
    measurementId: 'G-JK4GXFZSBZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCePqcuNYer3bWoELrVgCm3stBJwptrIXc',
    appId: '1:275997925238:android:7808bcc0752c1efe8aa457',
    messagingSenderId: '275997925238',
    projectId: 'edumate-4a475',
    databaseURL: 'https://edumate-4a475-default-rtdb.firebaseio.com',
    storageBucket: 'edumate-4a475.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBeH-Z2-OpefR3IWqoVIEtLyGYkuO-osc',
    appId: '1:275997925238:ios:75c5645d4222a17c8aa457',
    messagingSenderId: '275997925238',
    projectId: 'edumate-4a475',
    databaseURL: 'https://edumate-4a475-default-rtdb.firebaseio.com',
    storageBucket: 'edumate-4a475.appspot.com',
    iosBundleId: 'com.rubixx.edumate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBeH-Z2-OpefR3IWqoVIEtLyGYkuO-osc',
    appId: '1:275997925238:ios:4adfc085d73a75f98aa457',
    messagingSenderId: '275997925238',
    projectId: 'edumate-4a475',
    databaseURL: 'https://edumate-4a475-default-rtdb.firebaseio.com',
    storageBucket: 'edumate-4a475.appspot.com',
    iosBundleId: 'com.rubixx.edumate.RunnerTests',
  );
}
